### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by Daniel-Mietchen** [andreaspacher/openeditors#2]
to clarify reusability

**Comment by chartgerink** [comment]
I think it's CC0 based off the website. Maybe it would help to add a PR? ☺️ 

![image](https://user-images.githubusercontent.com/2946344/111638248-6f12aa00-87fa-11eb-957d-4c31be08b953.png)

**Comment by andreaspacher** [comment]
Thank you, @Daniel-Mietchen, for the suggestion to add the license formally (done with 7399238feeaba632f847cc59e0311e5dd64f890c); and thank you, @chartgerink, for your help!
