### ISSUE TITLE
Create a release of this repo

### ISSUE THREAD

**Issue by Daniel-Mietchen** [andreaspacher/openeditors#3]
So as to facilitate reuse.

[Here](https://guides.github.com/activities/citable-code/) is a description of the workflow to do this via Zenodo.

**Comment by andreaspacher** [comment]
Thanks for the hint, Daniel!

Done: [![DOI](https://zenodo.org/badge/340627338.svg)](https://zenodo.org/badge/latestdoi/340627338)
